### ISSUE TITLE
Upon VM reboot via Virtual Box, DHCP no longer works

### ISSUE THREAD

**Issue by Diane-cumulus** [CumulusNetworks/cldemo-netq#13]
After installing this demo and the VMs are powered off, upon power back on, DHCP does not work for the eth0 ports.

1.  Install Demo
2.  Everything works fine
3.  Power off VMs via virtual box
4.  Reboot VMs (oob-mgmt-server first, then switch, then rest of VMs)
5.  DHCP does not work for the eth0 port (also tried ifdown/ifup on eth0, did not fix), and none of the switch/server VMs are reachable from the oob-mgmt-server.
6. Statically configuring the IP addresses fixes the issue.

**Comment by plumbis** [comment]
dhcpd service is not enabled by default on oob-server. I adjusted the provision script.

Please try again with this branch 
https://github.com/CumulusNetworks/cldemo-netq/tree/dhcpd-fix

I'll merge if it works.

**Comment by Diane-cumulus** [comment]
I just tested this on leaf01 (only) - and it worked.  Thanks!
