### ISSUE TITLE
NetQ version incorrect

### ISSUE THREAD

**Issue by DianePatton** [CumulusNetworks/cldemo-netq#15]
Hi Pete-
The switch NetQ agent versions are still at 1.2 whereas the servers are 1.2.1.
This is because CL 3.5 comes with NetQ 1.2 and they were not upgraded.
To make them consistent, you will need to add the repo:  deb http://apps3.cumulusnetworks.com/repos/deb CumulusLinux-3 netq-1.2  (this does pull down 1.2.1)    and install cumulus-netq.  If you want me to do this, let me know.

**Comment by plumbis** [comment]
Resolved with lastest commit.

**Comment by yusufq8** [comment]
from where to download netq1.4 box (cumulus-netq-server-1.4.1-ts-amd64-libvirt.box) ? and how to test with cldemo-vagrant ref topology

**Comment by adeg** [comment]
Hi @yusufq8. You need to log in to www.cumulusnetworks.com with your account and then access your dashboard (_My dashboard_ link in the dropdown menu when you click the link _Welcome, $yourname_ in the upper right corner of the Cumulus webpage. Then go to the Downloads section, select _NetQ Virtual_ for Product, select the version, then choose _Vagrant_ as the hypervisor and finally _libvirt_ for Provider. Then you will be provided with the download button for the box you've requested. I hope this helps.

**Comment by yusufq8** [comment]
Hi @adeg i have followed your instruction but on my dashboard download i am getting only cumulus vx download option.

**Comment by adeg** [comment]
@yusufq8 I recommend contacting your local representative to see what could be the reason. If you're in the EMEA region, then you can contact me at anton@cumulusnetworks.com. Or email sales@cumulusnetworks.com if you're in some other region.
