### ISSUE TITLE
Incorrect download link for netq-1.4 telemetry server. 

### ISSUE THREAD

**Issue by smattoo** [CumulusNetworks/cldemo-netq#21]
Not able to download the netq server as metioned below.

Download the NetQ Telemetry Server from https://cumulusnetworks.com/downloads/#product=NetQ%20Virtual&hypervisor=Vagrant. You need to be logged into the site to access this. Choose NetQ 1.4.

The Product dropdown **does not** show **NetQ** as an option. It only shows Cumulus VX.

![CumulusNetworks_cldemo_netq](https://user-images.githubusercontent.com/2851191/74087785-a110f300-4ab5-11ea-8db3-1b7f73a461d0.png)

**Comment by petercrocker** [comment]
@smattoo NetQ 1.X has been depreciated, and replaced with a newer 2.X version. You'll need to reach out to a Cumulus account team to get the current image for testing. You can also reach out on slack to get in touch: https://slack.cumulusnetworks.com/
