### ISSUE TITLE
citc ansible.cfg file

### ISSUE THREAD

**Issue by kwitherstine** [CumulusNetworks/cldemo-netq#5]
need to add ansible.cfg file in citc repo to run setup.yml

**Comment by kwitherstine** [comment]
I see the ansible.cfg file in the repo, for some reason it didn't copy down to the citc oob-mgmt-server

**Comment by kwitherstine** [comment]
this issue is specific to the citc branch

**Comment by plumbis** [comment]
the current ansible.cfg has global settings that don't exist yet, so it fails on the setup, but will work on the demo folder. Fix is likely to keep hosts and ansible.cfg as local files for citc setup and write global settings for demos.

**Comment by plumbis** [comment]
This should be fixed by commit e932c59fdef97e6862c23877de83038e22a7d8c2
