### ISSUE TITLE
setup.yml clone tasks fail

### ISSUE THREAD

**Issue by kwitherstine** [CumulusNetworks/cldemo-netq#6]
<img width="1136" alt="screenshot 2017-10-08 20 09 51" src="https://user-images.githubusercontent.com/12203027/31322871-bb2e0198-ac64-11e7-8cd4-480fa8941540.png">

**Comment by kwitherstine** [comment]
this issue is specific to the citc demo

**Comment by plumbis** [comment]
This needs error handling for a double git clone. Likely a check to see if the directory already exists and then an ansible when to only run the clone step when they don't exist.

**Comment by plumbis** [comment]
setup now checks to see if the github repos have already been cloned before creating. /etc/ansible is also created before copy steps now. Fixed by 2272043800bc5a4a1e744d5f89a1b3f1a7c00902 and 4dadae434a01da0d203c48cf25370ff3c86773be
