### ISSUE TITLE
citc branch: setup.yml copy ansible.cfg task error

### ISSUE THREAD

**Issue by kwitherstine** [CumulusNetworks/cldemo-netq#7]
destination directory of /etc/ansible does not exist

<img width="1097" alt="screenshot 2017-10-08 20 35 16" src="https://user-images.githubusercontent.com/12203027/31323119-57f17c6e-ac68-11e7-96e0-0342b338c5ab.png">

**Comment by plumbis** [comment]
Fixed as part of fixes for #5
